language: node_js
node_js:
  - "10"
script: npm run docs:build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: docs/.vuepress/dist
  on:
    branch: master