name: Check CLA
on:
  - pull_request
  - push

jobs:
  check-cla:
    runs-on: ubuntu-latest
    name: Verify contributor

    steps:
    - uses: tidev/tidev-cla-action@v1.2.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
