---
name: 'Deploy'

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [ regen-docs ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: titanium-docs

    steps:
      # third-party action that cancels previous runs
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: titanium-docs

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: titanium_mobile
          repository: tidev/titanium_mobile

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.map
          repository: tidev/ti.map

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.facebook
          repository: tidev/ti.facebook

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.coremotion
          repository: tidev/ti.coremotion

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.crypto
          repository: tidev/ti.crypto

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.urlsession
          repository: tidev/ti.urlsession

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: titanium-identity
          repository: tidev/titanium-identity

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.playservices
          repository: tidev/ti.playservices

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.geofence
          repository: tidev/ti.geofence

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: tidev.ble
          repository: tidev/tidev.ble

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: tidev.bluetooth
          repository: tidev/tidev.bluetooth

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: tidev.https
          repository: tidev/tidev.https

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: tidev.encrypteddatabase
          repository: tidev/tidev.encrypteddatabase

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: titanium-web-dialog
          repository: tidev/titanium-web-dialog

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ti.barcode
          repository: tidev/ti.barcode

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: titanium-apple-sign-in
          repository: tidev/titanium-apple-sign-in

      - uses: actions/setup-node@v2
        with:
          node-version: '16'

      - run: npm ci
      - run: |
          npm run docs:metadata -- ../ti.map/apidoc ../ti.facebook/apidoc ../ti.coremotion/apidoc ../ti.crypto/apidoc ../ti.urlsession/apidoc ../titanium-identity/apidoc ../ti.playservices/apidoc ../ti.geofence/apidoc ../tidev.ble/apidoc ../tidev.bluetooth/apidoc ../tidev.https/apidoc ../tidev.encrypteddatabse/apidoc ../titanium-web-dialog/apidoc ../ti.barcode/apidoc ../titanium-apple-sign-in/apidoc
          npm run docs:migrate  -- ../ti.map/apidoc ../ti.facebook/apidoc ../ti.coremotion/apidoc ../ti.crypto/apidoc ../ti.urlsession/apidoc ../titanium-identity/apidoc ../ti.playservices/apidoc ../ti.geofence/apidoc ../tidev.ble/apidoc ../tidev.bluetooth/apidoc ../tidev.https/apidoc ../tidev.encrypteddatabse/apidoc ../titanium-web-dialog/apidoc ../ti.barcode/apidoc ../titanium-apple-sign-in/apidoc

      - uses: stefanzweifel/git-auto-commit-action@v4

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          branch: 'main'
          git_remote_url: 'ssh://dokku@titaniumsdk.com:22/titaniumsdk.com'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
