name: API Docs
on:
  push:
    branches:
    - master
    - "[0-9]+_[0-9]+_X"
    - actions_tests
  pull_request:

runs:
  using: composite
  steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
